/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenetre;

import static Fenetre.FenetrePrincipale.*;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Pierre
 */
public class FenetreMultiThreshold extends javax.swing.JFrame implements ChangeListener {

    FenetrePrincipale fp; 
    BufferedImage img; 
    ImageIcon imageIcon;
    ImageIcon icontmp; 
    BufferedImage bimtmp; 
    ImageIcon icon;
    
    /**
     * Creates new form FenetreMultiThreshold
     */
    public FenetreMultiThreshold(FenetrePrincipale f) {
        initComponents();
        fp = f; // fenetre principale 
        
        Slide1.addChangeListener(this); 
        Slide2.addChangeListener(this);
        Slide3.addChangeListener(this); 
        
        img = copyImage(fp.bimgSrc); 
        imageIcon = new ImageIcon(img); 
        // on affiche direct l'image dans le label dest 
        /*fp.ImageDst.setIcon(imageIcon); 
        fp.bimgDst = img; */
        
        icontmp = (ImageIcon) fp.ImageSrc.getIcon(); 
        bimtmp = fp.getBufferedImage(icontmp); 
    }

    private FenetreMultiThreshold() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Slide1 = new javax.swing.JSlider();
        Slide2 = new javax.swing.JSlider();
        Slide3 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        val1 = new javax.swing.JLabel();
        val2 = new javax.swing.JLabel();
        val3 = new javax.swing.JLabel();
        valMin1 = new javax.swing.JTextField();
        valMin2 = new javax.swing.JTextField();
        valMin3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        valMax1 = new javax.swing.JTextField();
        valMax2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        valMax3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        okButton1 = new javax.swing.JButton();
        okButton2 = new javax.swing.JButton();
        okButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Multi Threshold");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Multi Threshold");

        Slide1.setMaximum(255);
        Slide1.setValue(125);
        Slide1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Slide1StateChanged(evt);
            }
        });

        Slide2.setMaximum(255);
        Slide2.setValue(125);
        Slide2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Slide2StateChanged(evt);
            }
        });

        Slide3.setMaximum(255);
        Slide3.setValue(125);
        Slide3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Slide3StateChanged(evt);
            }
        });

        jLabel2.setText("0");

        jLabel3.setText("255");

        jLabel4.setText("255");

        jLabel5.setText("255");

        jLabel6.setText("0");

        jLabel7.setText("0");

        val1.setText("  ");

        val2.setText("  ");

        val3.setText("  ");

        jLabel14.setText("De:");

        jLabel15.setText("De:");

        jLabel16.setText("De:");

        jLabel17.setText("A:");

        jLabel18.setText("A:");

        jLabel19.setText("A:");

        okButton1.setText("Ok");
        okButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButton1ActionPerformed(evt);
            }
        });

        okButton2.setText("Ok");
        okButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButton2ActionPerformed(evt);
            }
        });

        okButton3.setText("Ok");
        okButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(valMin1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(valMin2)
                    .addComponent(valMin3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valMax1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Slide1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(val1)
                                .addGap(131, 131, 131)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valMax2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valMax3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(val3)
                                        .addGap(132, 132, 132)
                                        .addComponent(jLabel5))
                                    .addComponent(Slide3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(val2)
                                .addGap(131, 131, 131)
                                .addComponent(jLabel4))
                            .addComponent(Slide2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okButton1)
                    .addComponent(okButton2)
                    .addComponent(okButton3))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(227, 227, 227))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(okButton1)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(valMax1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17)
                                        .addComponent(valMin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(val1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Slide1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(val2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Slide2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(okButton2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(valMax2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18)
                                .addComponent(valMin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(okButton3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(valMax3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)
                                .addComponent(valMin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(val3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Slide3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Slide1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Slide1StateChanged
        // TODO add your handling code here:
        try { 
            int valm = Integer.parseInt(valMin1.getText()); 
            int valM = Integer.parseInt(valMax1.getText()); 
            if(!valMin1.getText().equals("") && !valMax1.getText().equals("") && valm < valM) { 
                val1.setText(String.valueOf(Slide1.getValue()));
                Threshold(Slide1.getValue(), valm, valM); 
            }
        } catch (NumberFormatException ex) { } 
    }//GEN-LAST:event_Slide1StateChanged

    private void Slide2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Slide2StateChanged
        // TODO add your handling code here:
        try { 
            int valm = Integer.parseInt(valMin2.getText()); 
            int valM = Integer.parseInt(valMax2.getText()); 
            if(!valMin2.getText().equals("") && !valMax2.getText().equals("") && valm < valM) { 
                val2.setText(String.valueOf(Slide2.getValue()));
                Threshold(Slide2.getValue(), valm, valM); 
            }
        } catch (NumberFormatException ex) { } 
    }//GEN-LAST:event_Slide2StateChanged

    private void Slide3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Slide3StateChanged
        // TODO add your handling code here:
        try { 
            int valm = Integer.parseInt(valMin3.getText()); 
            int valM = Integer.parseInt(valMax3.getText()); 
            if(!valMin3.getText().equals("") && !valMax3.getText().equals("") && valm < valM) { 
                val3.setText(String.valueOf(Slide3.getValue())); 
                Threshold(Slide3.getValue(), valm, valM); 
            }
        } catch (NumberFormatException ex) { } 
    }//GEN-LAST:event_Slide3StateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // réactive les boutons de la fentre principale 
        fp.enableAll(true); 
    }//GEN-LAST:event_formWindowClosing

    private void okButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButton1ActionPerformed
        // TODO add your handling code here:
        bimtmp = img; 
        icontmp = new ImageIcon(bimtmp); 
    }//GEN-LAST:event_okButton1ActionPerformed

    private void okButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButton2ActionPerformed
        // TODO add your handling code here:
        bimtmp = img; 
        icontmp = new ImageIcon(bimtmp); 
    }//GEN-LAST:event_okButton2ActionPerformed

    private void okButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButton3ActionPerformed
        // TODO add your handling code here:
        bimtmp = img; 
        icontmp = new ImageIcon(bimtmp); 
    }//GEN-LAST:event_okButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreMultiThreshold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreMultiThreshold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreMultiThreshold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreMultiThreshold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreMultiThreshold().setVisible(true);
            }
        });
    }

    @Override
    public void stateChanged(ChangeEvent e) {
    }

    private void Threshold(int val, int valm, int valM) { 
        try {        
            icon = icontmp; 
            img = fp.getBufferedImage(icon); 
            
            int width = img.getWidth(); 
            int height = img.getHeight();

            for (int y = 0; y < height; y++) 
            { 
                for (int x = 0; x < width; x++) 
                { 
                    int p = img.getRGB(x,y); 

                    int a = (p>>24)&0xff; 
                    int r = (p>>16)&0xff;
                    int g = (p>>8)&0xff; 
                    int b = p&0xff; 
                    
                    int avg = (r+g+b)/3; 

                    if(avg >= valm && avg <= valM)
                    {
                        avg = val;
                    }

                    a = 255; // opaque, pour etre sur
                    p = (a<<24) | (avg<<16) | (avg<<8) | avg; 
                    img.setRGB(x, y, p); 
                } 
            }
            // on l'affiche sur l'image dst 
            fp.bimgDst = img; 
            fp.ImageDst.setIcon(new ImageIcon(img)); 
            
            fp.updateHistogram(fp.histoImg2, fp.ImageDst); 
        } catch (NumberFormatException e) { } 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider Slide1;
    private javax.swing.JSlider Slide2;
    private javax.swing.JSlider Slide3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton okButton1;
    private javax.swing.JButton okButton2;
    private javax.swing.JButton okButton3;
    private javax.swing.JLabel val1;
    private javax.swing.JLabel val2;
    private javax.swing.JLabel val3;
    private javax.swing.JTextField valMax1;
    private javax.swing.JTextField valMax2;
    private javax.swing.JTextField valMax3;
    private javax.swing.JTextField valMin1;
    private javax.swing.JTextField valMin2;
    private javax.swing.JTextField valMin3;
    // End of variables declaration//GEN-END:variables
}
